module.exports = {
  //SERVER URLS
  SERVER_URL0: "http://localhost:3000",
  UPLOADS_SUBPATH: "api/uploads",
  SERVER_URL: "https://urbanapplause.flannerykj.com",

  // AUTH ACTIONS
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  REGISTER_RESET: "REGISTER_RESET",
  LOGIN_RESET: "LOGIN_RESET",


  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER_RESET: "REGISTER_RESET",
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
  AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

  // WORK ACTIONS
  SET_NEW_FILES: "SET_NEW_FILES",
  AWAIT_IMAGE_UPLOAD_RESPONSE: "AWAIT_IMAGE_UPLOAD_RESPONSE",
  IMAGE_UPLOAD_SUCCESS: "IMAGE_UPLOAD_SUCCESS",

  REQUEST_WORKS_DATA: "REQUEST_WORKS_DATA",
  RECEIVE_WORKS_DATA: "RECEIVE_WORKS_DATA",

  REQUEST_WORK_DATA: "REQUEST_WORK_DATA",
	RECEIVE_WORK_DATA: "RECEIVE_WORK_DATA",
	AWAIT_NEW_WORK_RESPONSE: "AWAIT_NEW_WORK_RESPONSE",
  RECEIVE_NEW_WORK_RESPONSE: "RECEIVE_NEW_WORK_RESPONSE",

	FAILED_NEW_WORK_RESPONSE: "FAILED_NEW_WORK_RESPONSE",
	START_WORK_EDIT: "START_WORK_EDIT",
	FINISH_WORK_EDIT: "FINISH_WORK_EDIT",
  SUBMIT_WORK_EDIT: "SUBMIT_WORK_EDIT",

  // COMMENT ACTIONS

  REQUEST_COMMENTS_DATA: "REQUEST_COMMENTS_DATA",
  RECEIVE_COMMENTS_DATA: "RECEIVE_COMMENTS_DATA",

	AWAIT_NEW_COMMENT_RESPONSE: "AWAIT_NEW_COMMENT_RESPONSE",
  RECEIVE_NEW_COMMENT_RESPONSE: "RECEIVE_NEW_COMMENT_RESPONSE",
  FAILED_NEW_COMMENT_RESPONSE: "FAILED_NEW_COMMENT_RESPONSE",

	START_COMMENT_EDIT: "START_COMMENT_EDIT",
	FINISH_COMMENT_EDIT: "FINISH_COMMENT_EDIT",
  SUBMIT_COMMENT_EDIT: "SUBMIT_COMMENT_EDIT",

  // ARTIST ACTIONS
  REQUEST_ARTISTS_DATA: "REQUEST_ARTISTS_DATA",
  RECEIVE_ARTISTS_DATA: "RECEIVE_ARTISTS_DATA",

  REQUEST_ARTIST_DATA: "REQUEST_ARTIST_DATA",
  RECEIVE_ARTIST_DATA: "RECEIVE_ARTIST_DATA",
	AWAIT_NEW_ARTIST_RESPONSE: "AWAIT_NEW_ARTIST_RESPONSE",
	RECEIVE_NEW_ARTIST_RESPONSE: "RECEIVE_NEW_ARTIST_RESPONSE",
	START_ARTIST_EDIT: "START_ARTIST_EDIT",
	FINISH_ARTIST_EDIT: "FINISH_ARTIST_EDIT",
  SUBMIT_ARTIST_EDIT: "SUBMIT_ARTIST_EDIT",

  //USER ACTIONS
  //
  REQUEST_USERS_DATA: "REQUEST_USERS_DATA",
  RECEIVE_USERS_DATA: "RECEIVE_USERS_DATA",
  REQUEST_USER_DATA: "REQUEST_USER_DATA",
	RECEIVE_USER_DATA: "RECEIVE_USER_DATA",
	AWAIT_NEW_USER_RESPONSE: "AWAIT_NEW_USER_RESPONSE",
	RECEIVE_NEW_USER_RESPONSE: "RECEIVE_NEW_USER_RESPONSE",
	START_USER_EDIT: "START_USER_EDIT",
	FINISH_USER_EDIT: "FINISH_USER_EDIT",
  SUBMIT_USER_EDIT: "SUBMIT_USER_EDIT",
};


